/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}

  // you can add a canvas by it's ID...
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();
  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menu
*/
$('#dropdown li').on('click', function(){
    alert($(this).text());
    $('button').text($(this).text());
    myweather($(this).attr("id"));
});

$(function(){
  myweather('Taipei City');
});

 var myweather = function(city) {
     $.getJSON(
         'https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D"' + city + '")&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys', {},
         function(data, status) {
             var date = data.query.results.channel.item.condition.date;
             date = date.split(' ');
             console.log('date', data.query.results.channel.item.condition.date);
             console.log('weather', data.query.results.channel.item.condition.text);
             $('.date').text(data.query.results.channel.item.forecast[0].date);
             $('.temperature').text(Math.round(tempftoc(data.query.results.channel.item.condition.temp)));
             $('.weather').text(" "+data.query.results.channel.item.condition.text);
             
             $('#date1').text(data.query.results.channel.item.forecast[1].date);
             $('#temp1').text(tempftoc(data.query.results.channel.item.forecast[1].low) + ' - ' + tempftoc(data.query.results.channel.item.forecast[1].high));
             $('#date2').text(data.query.results.channel.item.forecast[2].date);
             $('#temp2').text(tempftoc(data.query.results.channel.item.forecast[2].low) + ' - ' + tempftoc(data.query.results.channel.item.forecast[2].high));
             $('#date3').text(data.query.results.channel.item.forecast[3].date);
             $('#temp3').text(tempftoc(data.query.results.channel.item.forecast[3].low) + ' - ' + tempftoc(data.query.results.channel.item.forecast[3].high));
                          
             weathericon("today",data.query.results.channel.item.condition.text,data.query.results.channel.item.condition.date);
             weathericon("day1",data.query.results.channel.item.forecast[1].text,data.query.results.channel.item.condition.date);
             weathericon("day2",data.query.results.channel.item.forecast[2].text,data.query.results.channel.item.condition.date);
             weathericon("day3",data.query.results.channel.item.forecast[3].text,data.query.results.channel.item.condition.date);

         }
     );
 };

var tempftoc = function(t) {
     return Math.round((t-32)*5/9) ;
}

var weathericon = function(day,weather,time){
     if(weather.search("Sunny") >= 0){
      skycons.set(day, Skycons.CLEAR_DAY);
     }
     else if(weather.search("Clear") >= 0){
      skycons.set(p1, Skycons.CLEAR_NIGHT);
     }
     else if(weather.search("Cloudy") >= 0){
      if(weather.search("Partly") >= 0 && time.search("am") >= 0){
        skycons.set(day, Skycons.PARTLY_CLOUDY_DAY);
      }
      else if (weather.search("Partly") >=0 && time.search("pm") >= 0){
        skycons.set(day, Skycons.PARTLY_CLOUDY_NIGHT);
      }
      else{
        skycons.set(day, Skycons.CLOUDY);
      }
     }
     else if(weather.search("Rain") >= 0 || weather.search("Shower") >= 0 || weather.search("Storm") >= 0){
      skycons.set(day, Skycons.RAIN);
     }
     else if(weather.search("Sleet") >= 0){
      skycons.set(day, Skycons.SLEET);
     }
     else if(weather.search("Snow") >= 0){
      skycons.set(day, Skycons.SNOW);
     }
     else if(weather.search("Windy") >= 0){
      skycons.set(day, Skycons.WIND);
     }
     else if(weather.search("Foggy") >= 0){
      skycons.set(day, Skycons.FOG);
     }
     
}
